name = "linkp-worker"
main = "src/index.ts"
compatibility_date = "2024-11-14"

compatibility_flags = [ "nodejs_compat" ]

# route = { pattern = "linkp.co", custom_domain = true }

# [vars]
# Default environment (development)
[vars]
NODE_ENV = "development"
CORS_ORIGIN = "http://localhost:3000,https://linkp-website.pages.dev,https://linkp.co"

# Production environment
[env.production]
[env.production.vars]
name = "linkp-worker"
NODE_ENV = "production"
CORS_ORIGIN = "https://linkp.co"

# Staging environment
[env.staging]
[env.staging.vars]
name = "linkp-worker-staging"
NODE_ENV = "staging"
CORS_ORIGIN = "https://staging.linkp.co,https://linkp-website.pages.dev"



[[kv_namespaces]]
binding = "linkp_instagram_queue_fetching"
id = "fcb00289787c4d3f9fbf61ee1d46ea79"
preview_id="a5c2b208f6444e2996b828c2420849d6"

[[kv_namespaces]]
binding = "linkp_default_kv"
id = "4b01d5b797b049d8a5e7b6fe5bf6d2dc"



# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [ai]
# binding = "AI"

[observability]
enabled = true
head_sampling_rate = 1
