import type { Metadata } from "next";
import "../../globals.css";
import { dmSans, newKansas, nunSans } from "@/public/assets/fonts/fonts";

export const metadata: Metadata = {
  title: "Onboarding for Linkp",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body
        className={`${nunSans.variable} ${newKansas.variable} ${dmSans.variable}`}
      >
        <div className="h-dvh min-w-screen flex flex-col items-center">
          <h1 className="absolute top-2 font-heading text-2xl">Linkp</h1>
          {children}
        </div>
      </body>
    </html>
  );
}
