import type { Metadata } from "next";
import "../../globals.css";
import { dmSans, newKansas, nunSans } from "@/public/assets/fonts/fonts";

export const metadata: Metadata = {
  title: "Onboarding for Linkp",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return <main>{children}</main>;
}
