// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv cloudflare-env.d.ts`

interface CloudflareEnv {
	NEXT_CACHE_WORKERS_KV: KVNamespace;
	NEXTJS_ENV: string;
	AUTH_SECRET: string;
	NEXTAUTH_URL: string;
	AUTH_GOOGLE_ID: string;
	AUTH_GOOGLE_SECRET: string;
	NODE_ENV: string;
	DATABASE_URL: string;
	NEXT_PUBLIC_API_BASE_URL: string;
	CLOUDFLARE_ACCOUNT_ID: string;
	CLOUDFLARE_API_TOKEN: string;
	NEON_API_KEY: string;
	GH_TOKEN: string;
	NEON_PROJECT_ID: string;
	NEXT_PUBLIC_POSTHOG_KEY: string;
	NEXT_PUBLIC_POSTHOG_HOST: string;
	POSTHOG_API_KEY: string;
	POST_PROJECT_ID: string;
	INSTAGRAM_ACCESS_TOKEN: string;
	INSTAGRAM_APP_ID: string;
	INSTAGRAM_APP_SECRET: string;
	INSTAGRAM_VERIFY_TOKEN: string;
	NEXT_CACHE_DO_QUEUE_REVALIDATION_TIMEOUT_MS: string;
	NEXT_CACHE_DO_QUEUE_MAX_CONCURRENT: string;
	NEXT_CACHE_D1: D1Database;
	WORKER_SELF_REFERENCE: Fetcher;
	ASSETS: Fetcher;
}
