import type { Metadata } from "next";
import "./globals.css";
import { dmSans, newKansas, nunSans } from "@/public/assets/fonts/fonts";
// import { initializeTemplates } from "@/lib/templates/init";
import { Toaster } from "@/components/ui/toaster";
import { AuthProvider } from "@/providers/session-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// // Initialize templates at the module level
// if (typeof window === "undefined") {
//   // Only run on server-side
//   initializeTemplates();
// }

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Initialize templates at app start
  // initializeTemplates();

  return (
    <html lang="en">
      <body
        className={`${nunSans.variable} ${newKansas.variable} ${dmSans.variable}`}
      >
        {children}
        {/* <Toaster /> */}
      </body>
    </html>
  );
}
