name: Production Deployment

on:
  push:
    branches:
      - "main"

env:
  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
  CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      # Run migrations on production database
      - name: Run Database Migrations
        working-directory: ./apps/linkp-website
        run: pnpm run db:migrate
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      # Build and deploy the NextJS application
      - name: Build NextJS Project
        working-directory: ./apps/linkp-website
        run: |
          NEXT_PUBLIC_CF_PAGES=1 \
          NEXT_PUBLIC_CF_PAGES_BRANCH=main \
          pnpm run pages:build

      - name: Deploy NextJS to Production
        id: deploy-nextjs
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy
          workingDirectory: "./apps/linkp-website"

      # Worker Deployment
      - name: Deploy Worker to Production
        id: deploy-worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: ./apps/linkp-worker
          command: deploy --env production
          # preCommands: |
          #   # Delete existing secret if it exists
          #   npx wrangler secret delete DATABASE_URL --env production || yes
          #   # Add new secret
          #   echo "${{ secrets.DATABASE_URL }}" | npx wrangler secret put DATABASE_URL --env production
      # Verify and log successful deployment
      - name: Log Deployment Status
        run: |
          echo "✅ Production deployment completed successfully"
          echo "Frontend: https://linkp-website.pages.dev"
          echo "Worker: https://linkp-worker.sayyedabood69.workers.dev"
