name: Production Deployment

on:
  push:
    branches:
      - "main"

env:
  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
  CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      # Run migrations on production database
      - name: Run Database Migrations
        working-directory: ./apps/linkp-website
        run: pnpm run db:migrate
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      # Build and deploy the NextJS application
      - name: Build NextJS Project
        working-directory: ./apps/linkp-website
        run: |
          NEXT_PUBLIC_CF_PAGES=1 \
          NEXT_PUBLIC_CF_PAGES_BRANCH=main \
          pnpm run pages:build

      - name: Deploy NextJS to Production
        id: deploy-nextjs
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy
          workingDirectory: "./apps/linkp-website"

        # Worker Deployment with Versions
      - name: Upload New Worker Version
        id: upload-worker
        working-directory: ./apps/linkp-worker
        run: |
          # First, set the secret in the new version without deploying
          echo "${{ secrets.DATABASE_URL }}" | npx wrangler versions secret put DATABASE_URL

          # Upload new version (creates version without deploying)
          echo "Uploading new worker version..."
          VERSION_ID=$(npx wrangler versions upload | grep -oP 'id: \K[a-f0-9-]+')
          echo "version_id=$VERSION_ID" >> $GITHUB_OUTPUT

      - name: Deploy New Worker Version
        working-directory: ./apps/linkp-worker
        run: |
          # Deploy new version with 100% traffic
          echo "Deploying worker version ${{ steps.upload-worker.outputs.version_id }}..."
          npx wrangler versions deploy << EOF
          100
          ${{ steps.upload-worker.outputs.version_id }}
          EOF

      # Verify and log successful deployment
      - name: Log Deployment Status
        run: |
          echo "✅ Production deployment completed successfully"
          echo "Frontend: https://linkp-website.pages.dev"
          echo "Worker: https://linkp-worker.sayyedabood69.workers.dev"
